#! /bin/sh

while read xx ; do
if test "$xx" = "" ; then continue;
fi
echo === $xx
( echo open $xx 119
  sleep 5
  echo ihave IamSOk00l@podunk.edu
  sleep 4
  echo .
  echo quit
  sleep 1
  echo quit
) | telnet
done
